### ISSUE TITLE
Is it possible to use environment variables in config.yml?

### ISSUE THREAD

**Issue by moranbw** [adferrand/dnsrobocert#103]
Hi --First off great work on this and also the old incarnation of the project!

I'm working to migrate to dnsrobocert from the old project, and I was wondering if it is possible to use environment variables in the config.yml?  something like:

`email_account: ${LETSENCRYPT_USER_MAIL}`

I ask because I use this tool to inject environment variables into my container, so I don't have to store them in plain text on my server.  https://github.com/cyberark/summon

Perhaps there's a better way of thinking about how to protect my "secrets" with dnsrobocert, so I am all ears for alternatives.

**Comment by adferrand** [comment]
I have an alternative, that I describe here: https://github.com/adferrand/dnsrobocert/issues/27#issuecomment-597354628

It is basically to beeing able to define part or whole DNSroboCert configuration with environment variables, using a environment variable names pattern. Would it be sufficient for your use case?

**Comment by moranbw** [comment]
This looks like exactly what I'm looking for, thanks! Does this YAML <-> environment variable mapping explanation also live somewhere in the docs? I may have missed it.

I guess my main concern was this line from the documentation: **usage of the old environment variables and the domains.conf file is deprecated**.  But I guess this really does refer to the **old** environment variables, not this new mapping?

**Comment by adferrand** [comment]
Yes it refers to the old environment variables. However, the new one is not yet implemented. I am working on it, and hope to finish it by the end of this week.

**Comment by moranbw** [comment]
Awesome!  I'll keep an eye on new releases.

**Comment by gurumark** [comment]
@adferrand Is there any update on this item?

**Comment by adferrand** [comment]
Injecting environment variables in the configuration file is now supported with the new release 3.3.2.

This is independant from #27, that I will do later, and consists in a configuration through environment variables without any configuration file.

**Comment by moranbw** [comment]
This enhancement in 3.3.2 works great for my use-case -- thank you!!
