### ISSUE TITLE
Support for concatenating pems together

### ISSUE THREAD

**Issue by seanfarley** [adferrand/dnsrobocert#110]
For some projects, e.g. haproxy, I need to cat together the certs:

```
cat "${RENEWED_LINEAGE}/privkey.pem" "${RENEWED_LINEAGE}/fullchain.pem" > "${RENEWED_LINEAGE}/${domain}.pem"
```

Would it be possible to have a setting for this? I hesitate to make a PR for it because I could see taking a stand against adding more configuration options for functionality that could be done in a deploy hook script.

**Comment by adferrand** [comment]
Hello @seanfarley. Indeed, you can totally do it with a deploy hook. This can be setup with the `deploy_hook` parameter in each `certificate` section (https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#certificate-properties). Put the logic in a bash script, mount it in the docker (if you use the docker image), and specify its path to `deploy_hook`.

All variable environments exposed by Certbot are also set in the deploy hook, so `RENEWED_LINEAGE` in particular.

**Comment by seanfarley** [comment]
Righto, so does that mean you'd rather not want a config option? That's totally fine, just making sure.

**Comment by adferrand** [comment]
Yes I prefer to keep things as simple as possible, and not add an option when an alternative is possible. I already added too much of them (eg. PFX) ;).

**Comment by seanfarley** [comment]
Totally understand and no worries! I'll close the issue now :-)
