### ISSUE TITLE
GoDaddy: dnsrobocert.core.hooks; returned error code 1

### ISSUE THREAD

**Issue by CM2Walki** [adferrand/dnsrobocert#111]
Hey,

I'm receiving a HTTP 422 error when trying to request a certificate using the godaddy provider:

```
Waiting for verification...
Challenge failed for domain MYDOMAIN.com
dns-01 challenge for MYDOMAIN.com
Cleaning up challenges
Running manual-cleanup-hook command: /usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmpfkeqdw0m/dnsrobocert-runtime.yml" -l "MYDOMAIN.com"
Output from manual-cleanup-hook command python3:
acme:
  email_account: user@MYDOMAIN.com
  staging: true
certificates:
- domains:
  - '*.MYDOMAIN.com'
  profile: godaddy_profile
draft: false
profiles:
- name: godaddy_profile
  provider: godaddy
  provider_options:
    auth_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    auth_secret: YYYYYYYYYYYYYYYYY
```

```
manual-cleanup-hook command "/usr/bin/python3 -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmpfkeqdw0m/dnsrobocert-runtime.yml" -l "MYDOMAIN.com"" returned error code 1
Error output from manual-cleanup-hook command python3:
2020-06-06 12:08:53 ca425410cb5c __main__[13] ERROR Error while executing the `cleanup` hook:
2020-06-06 12:08:53 ca425410cb5c __main__[13] ERROR 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/MYDOMAIN.com/records/TXT
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 48, in main
    globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
  File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 125, in cleanup
    _txt_challenge(profile, token, domain, action="delete")
  File "/usr/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 174, in _txt_challenge
    Client(lexicon_config).execute()
  File "/usr/lib/python3.8/site-packages/lexicon/client.py", line 93, in execute
    return self.provider.delete_record(identifier, record_type, name, content)
  File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 118, in delete_record
    return self._delete_record(identifier=identifier, rtype=rtype, name=name, content=content)
  File "/usr/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 230, in _delete_record
    self._put('/domains/{0}/records/{1}'.format(domain, rtype), filtered_records)
  File "/usr/lib/python3.8/site-packages/lexicon/providers/base.py", line 148, in _put
    return self._request('PUT', url, data=data, query_params=query_params)
  File "/usr/lib/python3.8/site-packages/lexicon/providers/godaddy.py", line 291, in _request
    result.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.godaddy.com/v1/domains/MYDOMAIN.com/records/TXT
```

Some more info:
- https://api.godaddy.com/v1/domains/MYDOMAIN.com/records/TXT is returning the TXT records correctly.
- I followed the User Guide pretty much letter for letter.
- I tried upgrading GoDaddyPy, didn't help.

Manually adding a TXT record using lexicon is working as expected:
```
lexicon godaddy create "MYDOMAIN.com" TXT --name="foo" --content="bar" --auth-key="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" --auth-secret="YYYYYYYYYYYYYYYYY"
```

Is there anything I'm missing / I misconfigured?

**Comment by CM2Walki** [comment]
@adferrand I managed to track down & fix the issue. 

I started looking into the code after I saw [this issue](https://github.com/AnalogJ/lexicon/issues/518) over at lexicon.

This lead me to investigate the code in [hooks.py](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/hooks.py). And low and behold, the root dot/period is being added [here in line 160](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/hooks.py#L160). I removed it in my container for testing purposes and the challenge completed [almost] flawlessly.

Turns out the cleanup, the delete action in particular, of the challenge won't run on GoDaddy, because "[...] there is no delete DNS record function in the GoDaddy Domains API" (Source: http://pbxhacks.com/automating-lets-encrypt-ssl-certs-via-godaddy-dns-challenge/). So I ended up commenting [out the "delete" action here](https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/hooks.py#L125), after which the challenge completes without errors. This is however is not ideal because the TXT entry will obviously remain.

If you like I could open a PR that adds exceptions for the GoDaddy provider ("if Godaddy don't add the root dot in the FQDN & skip the cleanup"). Or I can leave it up to you, if you know of a prettier solution :).

**Comment by adferrand** [comment]
Hello @CM2Walki, the issues you observe here are due to regressions added to upstream in Lexicon project with version 3.3.24. We reverted these changes in 3.3.26. I am currently updating DNSroboCert with this new version, so the issues should vanish.

**Comment by CM2Walki** [comment]
Thanks man, I'll give it a go once the new release is out.

**Comment by adferrand** [comment]
New release is out!

**Comment by CM2Walki** [comment]
Sorry for the delay.

The new release fixed it. Thanks.
