### ISSUE TITLE
Support for Hurricane Electric DNS

### ISSUE THREAD

**Issue by solaris7x** [adferrand/dnsrobocert#113]
I couldn't find he.net unde[r Lexicon providers options for dnsrobocert](https://dnsrobocert.readthedocs.io/en/latest/providers_options.html#providers-options) but [pipy dns-lexicon](https://pypi.org/project/dns-lexicon/) has it available.
Can we expect support for Hurricane Electric or better off switching to other DNS hosting ?
Thank you for your time

**Comment by adferrand** [comment]
Hello! Actually, it is supported, and you can see the provider in the list under `henet` section. So you should be able to use it without issues.

**Comment by solaris7x** [comment]
I am sorry I must has missed it , thank you for help
