### ISSUE TITLE
Possible to support alternatives to LetsEncrypt?

### ISSUE THREAD

**Issue by polarathene** [adferrand/dnsrobocert#149]
Will this project only ever support LetsEncrypt? Or could it be open to supporting ACME-compatible alternatives such as [ZeroSSL](https://zerossl.com/letsencrypt-alternative/) or [step-ca](https://smallstep.com/blog/private-acme-server/)? (`step-ca` for private self-hosted ACME CA server, link shows example to configure certbot to use)

Looking over the README and docs here, the project seems to only focus on LetsEncrypt at present?

**Comment by FatGrizzly** [comment]
edit the acme directory at https://github.com/adferrand/dnsrobocert/blob/master/src/dnsrobocert/core/config.py and build yourself

**Comment by polarathene** [comment]
> and build yourself

You're responding to say I should fork and modify instead of feature request? I ended up using an alternative project that wasn't tied to a specific ACME provider.

> edit the acme directory

For anyone that would follow that suggestion, I assume you mean to modify this line?:

https://github.com/adferrand/dnsrobocert/blob/5a866fef5240a2f631a4b23c38d09d9f46fdac92/src/dnsrobocert/core/config.py#L125

**Comment by FatGrizzly** [comment]
> For anyone that would follow that suggestion, I assume you mean to modify this line?:

Yea, that line



> You're responding to say I should fork and modify instead of feature request? I ended up using an alternative project that wasn't tied to a specific ACME provider.
I had to say this because this issue has been open for 9 months and seems like no one replied, so I had to tell you that

**Comment by adferrand** [comment]
Or, you open a PR because I have no bandwith to develop currently, but I will be glad to review it and make a new release :)

**Comment by polarathene** [comment]
> Or, you open a PR because I have no bandwith to develop currently

I understand how that is, similar situation myself atm. Good to know a PR is welcomed!

Unfortunately I don't think I'll have any time for that as I was happy with the alternative I went with. I'll leave this open in case anyone else would be interested, or now that it's been answered I can close it?

> I had to say this because this issue has been open for 9 months and seems like no one replied, so I had to tell you that

@FatGrizzly this is a feature request / question, no harm in it staying open for anyone else who might be interested in the same (in this case it doesn't seem anyone else is).

If I were to make a change myself, I usually try to create a PR for it to merge back upstream.

**Comment by adferrand** [comment]
Sorry I misunderstood the purpose of this issue. In fact you can already do what you want, which is to target another CA server if I understand properly.

All you need is to define the configuration property `acme.directory_url`. See https://dnsrobocert.readthedocs.io/en/latest/configuration_reference.html#acme-section for more information.
