### ISSUE TITLE
Provider Support for Joker.com

### ISSUE THREAD

**Issue by Zerobian** [adferrand/dnsrobocert#193]
Hi,
this service look like what I'm searching for. I use traefik which is working fine so far, but I have several services which are needing pkcs#12 certificate files. Seems this gap could be closed with dnsrobocert.
Unfortunately my provider is not listed - joker.com.
Could you add this provider by any chance?

**Comment by adferrand** [comment]
Hello @Zerobian! DNSroboCert uses https://github.com/AnalogJ/lexicon to communicate with DNS providers. So Lexicon needs first a joker.com provider. I looked at the documentation, it seems that an API is available. Now the limited factor is usually that an access on the DNS providers API usually requires a paid account.

I could implement the provider in Lexicon if you provide me some credentials to access the API. You can reach me privately at https://spectrum.chat/dnsrobocert

**Comment by Zerobian** [comment]
Message send with needed information's.

**Comment by adferrand** [comment]
https://github.com/AnalogJ/lexicon/pull/636

**Comment by Zerobian** [comment]
Sorry I was busy this week.
Cert generation is working successful when the domain is not in the status "locked".

> manual-cleanup-hook command "/usr/local/bin/python -m dnsrobocert.core.hooks -t cleanup -c "/tmp/tmpfiw_pbyf/dnsrobocert-runtime.yml" -l "digitalmini.me"" returned error code 1
> Error output from manual-cleanup-hook command python:
> Error while executing the `cleanup` hook:
> Current status for domain digitalmini.me is: lock
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 42, in main
>     globals()[parsed_args.type](dnsrobocert_config, parsed_args.lineage)
>   File "/usr/local/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 149, in cleanup
>     _txt_challenge(profile, token, domain, action="delete")
>   File "/usr/local/lib/python3.8/site-packages/dnsrobocert/core/hooks.py", line 200, in _txt_challenge
>     Client(lexicon_config).execute()
>   File "/usr/local/lib/python3.8/site-packages/lexicon/client.py", line 67, in execute
>     self.provider.authenticate()
>   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/base.py", line 74, in authenticate
>     return self._authenticate()
>   File "/usr/local/lib/python3.8/site-packages/lexicon/providers/joker.py", line 84, in _authenticate
>     raise ValueError(f"Current status for domain {self.domain} is: {items[2]}")
> ValueError: Current status for domain digitalmini.me is: lock

Explanation for the domain locking feature:
> The protection of a domain name ("domain locking") provides an additional layer of security against unauthorized domain manipulation. It also prevents from fraudulent transfers.
> This feature keeps you safe from the notorious people known as domain hijackers. They often spot nice domain names to generate profit from them.
> If you decide you do need to unlock your domain (needed to transfer a domain to another registrar), simply log in to your account at Joker.com and remove the lock with the help of our 'Servicezone'.
> This procedure conforms to the ICANN regulations from November 12th, 2004.

Can you clarify the issue?
Traefik is working with domain locked for the DNS challange.

**Comment by adferrand** [comment]
OK I misinterpretated the locked state, assuming that is was a domain in some kind of read only mode, which consequently could not be edited.

I will fix that during the week end.

**Comment by Zerobian** [comment]
Works fine! I have successful tested it.
Thank you for your support and engagement. Please notify me, if support for joker.com is need.
