### ISSUE TITLE
Support for validating via CNAME (alias)

### ISSUE THREAD

**Issue by evilensky** [adferrand/dnsrobocert#230]
As described in the [EFF blog](https://www.eff.org/deeplinks/2018/02/technical-deep-dive-securing-automation-acme-dns-challenge-validation) there are lots of reasons to answer ACME challenge via a CNAME is desirable.

I would love to add support for this but am not 100% certain where to start. 

I started by abusing the [config dict](https://github.com/adferrand/dnsrobocert/blob/1621c825e0a1bc73bee7bab43897ea99312c9126/src/dnsrobocert/core/hooks.py#L181) and setting domain to "delegated_subdomain."  How may I turn this into a real config property?

I don't think this needs any extra logic except as config parameter because in the CNAME scenario there is no need to ever interact with original `domain` and `domain` should always make use of existing DNS provider hooks....maybe?

```
    delegated = profile.get("delegated_subdomain")

    if delegated:
        domain = delegated

    config_dict = {
        "action": action,
        "domain": domain,
        "type": "TXT",
        "name": "_acme-challenge.{0}.".format(domain),
        "content": token,
        "delegated": profile.get("delegated_subdomain"),
        "provider_name": provider_name,
        provider_name: provider_options,
    }
```

Thank you!

**Comment by adferrand** [comment]
I found a way: https://github.com/adferrand/dnsrobocert/pull/231

**Comment by evilensky** [comment]
Looking forward to it, thanks!
