### ISSUE TITLE
Feature request: check for certificate before regenerating.

### ISSUE THREAD

**Issue by HermannBjorgvin** [adferrand/dnsrobocert#39]
I have a slight problem that I noticed in developing an application using your great docker image. I hit the letsencrypt rate limit https://letsencrypt.org/docs/rate-limits/

Is it possible to skip generating a certificate if a valid certificate for the domain.conf domains is already present?

**Comment by HermannBjorgvin** [comment]
@adferrand yes I should have been using staging, it didn't occur to me before I hit the rate limit :)

It just occurred to me that if a cert was generated a short time ago it didn't make a ton of sense to renew it immediately. It would make the container I guess more idiot proof for people in my situation.

**Comment by charleszlu** [comment]
I submitted a PR (#50) for this as I have also run into the renewal limit when I was playing around with my stack. When the container is restarted from updating the stack, certbot is run immediately (and every time when scheduled).

**Comment by charleszlu** [comment]
Actually I'm a bit confused now. I have just checked on [https://tools.letsdebug.net/](url) that I hit the 5 Duplicate Certificate weekly limit from 5 pre-certificates which I don't quite understand where it came from.

**Comment by adferrand** [comment]
Hello! There is some confusion I think around when certificates are renewed here.

To be clear, upon startup, `certbot certonly ...` is invoked for each domain. However, this command does not renew the certificate, as Certbot detects that a certificate already exists, and is not due for renewal.

The two situations where an actual new issuance of a certificate, are:
1) If the list of sub-domains is modified for a given main domain
2) If the relevant line for a certificate in `domains.conf` is removed, then added back

In the first case, Certbot will see that even if the certificate is of the same name, the sub-domains changed, so a new request must be done. In the second case, my Docker, upon detection of a line removed, will delete and revoke the certificate. So adding the line back is a completely new certificate.
