### ISSUE TITLE
Feature Request - Support --reuse-key option

### ISSUE THREAD

**Issue by nightah** [adferrand/dnsrobocert#452]
As it currently stands private keys by default are rotated when a certificate renewal is performed.

Certbot has the ability to run with the [`--reuse-key`](https://certbot.eff.org/docs/using.html#certbot-command-line-options) option which avoids rotating the private key, this is especially useful for TLSA/DANE.

One can manually update the renewal `.conf` file for the specific cert and insert `reuse_key = True` under the `[renewalparams]` option however this seems to be lost somewhere in the process. I assume based on when the automatic renewals occur.

It would be fantastic if we had a `reusekey` option in the `certificates` configuration section which allows us to enable said option.

**Comment by nightah** [comment]
Thanks for including this @adferrand!

**Comment by adferrand** [comment]
You are welcome !
