### ISSUE TITLE
Renewal fails due to module error

### ISSUE THREAD

**Issue by Vertganti** [adferrand/dnsrobocert#518]
Investigating a certificate that had not been renewed I discovered from the logs that DNSroboCert/Certbot had encountered a DNS problem while trying to renew the certificate. The DNS problem might have been on our side, I cannot tell if it was. However, after the failed attempt DNSroboCert apparently crashed and did not start any renewal attempts anymore. After restarting the container today the certificate was successfully renewed and the container is running smoothly for now. I guess this crash might only happen in edge cases with DNS problems during renewal. I also cannot reproduce it, so I cannot tell if a newer version of DNSroboCert might already have fixed the issue (as can be seen from the logs below the running version was 3.11.0). 

Here is the relevant part of the log. Afterwards nothing was logged anymore:

    2021-09-07 16:33:30 69d4b82d847c dnsrobocert.core.utils[1] INFO Launching command: /opt/dnsrobocert/bin/python -m dnsrobocert.core.certbot renew -n --user-agent-comment DNSroboCert/3.11.0 --config-dir /etc/letsencrypt --deploy-hook "/opt/dnsrobocert/bin/python -m dnsrobocert.core.hooks -t deploy -c \"/tmp/tmp0_a1qsn1/dnsrobocert-runtime.yml\"" --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Processing /etc/letsencrypt/renewal/something.example.com.conf
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
    Renewing an existing certificate for something.example.com
    Hook '--manual-auth-hook' for something.example.com reported error code 1
    Hook '--manual-auth-hook' for something.example.com ran with error output:
    /usr/local/bin/python: Error while finding module specification for 'dnsrobocert.core.hooks' (ModuleNotFoundError: No module named 'dnsrobocert')

    Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
      Domain: something.example.com
      Type:   dns
      Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.something.example.com - check that a DNS record exists for this domain

    Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

    Hook '--manual-cleanup-hook' for something.example.com reported error code 1
    Hook '--manual-cleanup-hook' for something.example.com ran with error output:
    /usr/local/bin/python: Error while finding module specification for 'dnsrobocert.core.hooks' (ModuleNotFoundError: No module named 'dnsrobocert')
    Failed to renew certificate something.example.com with error: Some challenges have failed.
    All renewals failed. The following certificates could not be renewed:
      /etc/letsencrypt/live/something.example.com/fullchain.pem (failure)

    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    1 renew failure(s), 0 parse failure(s)
    Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /etc/letsencrypt/logs/letsencrypt.log or re-run Certbot with -v for more details.
    ----------
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
        self.run()
      File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/background.py", line 48, in run
        schedule.run_pending()
      File "/opt/dnsrobocert/lib/python3.9/site-packages/schedule/__init__.py", line 563, in run_pending
        default_scheduler.run_pending()
      File "/opt/dnsrobocert/lib/python3.9/site-packages/schedule/__init__.py", line 94, in run_pending
        self._run_job(job)
      File "/opt/dnsrobocert/lib/python3.9/site-packages/schedule/__init__.py", line 147, in _run_job
        ret = job.run()
      File "/opt/dnsrobocert/lib/python3.9/site-packages/schedule/__init__.py", line 466, in run
        ret = self.job_func()
      File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/background.py", line 70, in _renew_job
        certbot.renew(config_path, directory_path, lock)
      File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/certbot.py", line 122, in renew
        utils.execute(
      File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/utils.py", line 60, in execute
        raise error
      File "/opt/dnsrobocert/lib/python3.9/site-packages/dnsrobocert/core/utils.py", line 50, in execute
        call(command, shell=shell, env=env)
      File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/opt/dnsrobocert/bin/python', '-m', 'dnsrobocert.core.certbot', 'renew', '-n', '--user-agent-comment', 'DNSroboCert/3.11.0', '--config-dir', '/etc/letsencrypt', '--deploy-hook', '/opt/dnsrobocert/bin/python -m dnsrobocert.core.hooks -t deploy -c "/tmp/tmp0_a1qsn1/dnsrobocert-runtime.yml"', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs']' returned non-zero exit status 1.

**Comment by JanickGers85** [comment]
I'm running the latest docker version and I have the same problem.
I'm using Dynu DDNS

**Comment by Vertganti** [comment]
Happened again during the renewal on another host - same error, same stack trace. Since this is happening for others too this might not be due to a DNS issue at all. Reading a bit about virtual environments and the `-m` flag I think it could be due to the recent changes to the Dockerfile. In the [Debain base commit](https://github.com/adferrand/dnsrobocert/commit/12b9e6296e9d2eb376649537ebad6413b26c5aa5#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557) the installation routine was changed and [a virtual environment is now set up](https://github.com/adferrand/dnsrobocert/blob/12b9e6296e9d2eb376649537ebad6413b26c5aa5/Dockerfile#L24). I am guessing either the module is not installed in the virtual environment or the calls from the utils.call() function do not use the virtual environment?

**Comment by adferrand** [comment]
Indeed, I missed the problem of the hook python executable when switching to a virtual environment. I published a new version that switches back to an installation on the OS python distribution. So this problem should be fixed now.

**Comment by Vertganti** [comment]
Thank you! Our next automatic renewal should be at the end of this week, so I can confirm if it is working by next Monday.

**Comment by adferrand** [comment]
Yes, the certificate has been generated when `/opt/dnsrobocert/bin/python` was the python executable. The renewal should work now with the new version `3.14.0`.

**Comment by Vertganti** [comment]
With version `3.14.0` the following error appears:

    Renewing an existing certificate for something.example.com
    Hook '--manual-auth-hook' for something.example.com reported error code 1
    Hook '--manual-auth-hook' for something.example.com ran with error output:
     2021-11-16 15:46:10 dcb59097ff2f dnsrobocert.core.config[14] ERROR Configuration file /tmp/tmpakbzjqod/dnsrobocert-runtime.yml does not exist.
     Error occured while loading the configuration file, aborting the `auth` hook.

    Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
      Domain: something.example.com
      Type:   dns
      Detail: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.something.example.com - check that a DNS record exists for this domain

    Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

    Hook '--manual-cleanup-hook' for something.example.com reported error code 1
    Hook '--manual-cleanup-hook' for something.example.com ran with error output:
     2021-11-16 15:46:12 dcb59097ff2f dnsrobocert.core.config[16] ERROR Configuration file /tmp/tmpakbzjqod/dnsrobocert-runtime.yml does not exist.
     Error occured while loading the configuration file, aborting the `cleanup` hook.
    Failed to renew certificate something.example.com with error: Some challenges have failed.
    
Stack trace is the same. Restarting the container led to a successful renewal.

**Comment by adferrand** [comment]
Hello again @Vertganti. So once the container is restarted, the error vanishes? Can we consider this issue has fixed then?

**Comment by Vertganti** [comment]
It is temporarily fixed at least. I cannot confirm if it is permanently fixed yet or if it reappears on successive renewals. You can close the issue if you want and if the issue reappears I will reopen it. Otherwise I will close it once I am sure the issue does not reappear.

**Comment by adferrand** [comment]
Ok thanks !
