### ISSUE TITLE
certificate gets regenerated after restore from backup

### ISSUE THREAD

**Issue by thelittlebug** [adferrand/dnsrobocert#52]
hi, thank you for your wonderful project. i think it could fit my needs very well :)

as i'm fiddling arround i think i found a non documented side effect:
1. start with a clean vm with docker installed
2. run docker-letsencrypt-dns with a named volume
3. run a helper container and copy the data to s3
4. start with a clean vm with docker installed
5. run a helper container copy the data from s3 to the named volume
6. run docker-letsencrypt-dns with that named volume
7. the certificate gets regenerated

expected behavior: the certificate is here -> do not regenerate it

but if i replace point 4 with:

4.1. delete named volume
4.2. create named volume

then point 7 changes to:

7. the certificate does not get regenerated

thats the reason why i think this is a side effect. maybe some state is not in the containers /etc/letsencrypt directory?

could you clarify what else has to go into the backups except /etc/letsencrypt?

thx a lot

**Comment by adferrand** [comment]
Hello @thelittlebug ! Indeed, I think your very precise test workflow enlights a missing state in the container. In fact, Certbot uses also two other folders beside the configuration folder (`/etc/letsencrypt`): the log dir and the work dir.

And indeed, work dir is used to maintain some of the certbot state.

I think I will reconfigure Certbot in my docker to use two paths under `/etc/letsencrypt` for these folders. We will benefit from a persisted state and persisted logs.

I check and make a release.

**Comment by pascalandy** [comment]
I'm about the set this project on my stack.

1) In the container, I assume this is how it looks like right?

```
/etc/letsencrypt/domains.conf
/etc/letsencrypt/live/
/etc/letsencrypt/logs/
```

2) As I mount data all under `/etc/letsencrypt`, I should not have any issue went I have to re-build my cluster right?

```
docker run \
  --name letsencrypt-dns \
  --volume /etc/letsencrypt/domains.conf:/etc/letsencrypt/domains.conf \
  --volume /etc/letsencrypt:/etc/letsencrypt
  --env 'LETSENCRYPT_USER_MAIL=user@mail.org' \
  --env 'LEXICON_CLOUDFLARE_AUTH_USERNAME=user@mail.org' \
  --env 'LEXICON_CLOUDFLARE_AUTH_TOKEN=010101010101101010101010101' \
  adferrand/letsencrypt-dns
```

3) I'm trying to understand if it's the `/etc/letsencrypt/logs/` that cause the glitch described about?

Thank you very much for this awesome project!

**Comment by adferrand** [comment]
Hello, very sorry for the late response. The glitch was due to the `work` folder, that can influence also the renewal. Since you mount the whole `/etc/letsencrypt` folder, and that now `work` is inside this folder, you will not encounter any issue.
