### ISSUE TITLE
DST Root CA X3 expiration (September 2021)

### ISSUE THREAD

**Issue by DominikTrenz** [adferrand/dnsrobocert#530]
dnsrobocert seems to still create chains based on DST Root CA X3 which is expired and causes problems on some clients.
https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190
A known workaround is to use this parameter with certbot:
`
--preferred-chain "ISRG Root X1"
`
Can add this to the renewal process?
Thanks!

**Comment by tismoe** [comment]
I had the same issue. As a work-around, place `preferred-chain = ISRG Root X1` in `/etc/certbot/cli.ini`. This does the trick, if you're on at least [dnsrobocert 3.9.0](https://github.com/adferrand/dnsrobocert/blob/master/CHANGELOG.md#390---21032021) with [certbot 1.12.0](https://github.com/certbot/certbot/releases/tag/v1.12.0) respectively.

**Comment by adferrand** [comment]
No problem I do that today.

**Comment by adferrand** [comment]
I added the `--preferred chain ISRG Root X1` to all certbot commands. The problem should be fixed now.
