### ISSUE TITLE
please consider to add ecc cert option

### ISSUE THREAD

**Issue by hejaxian** [adferrand/dnsrobocert#577]
Nowadays, Certbot supports --key-type option, use the ecdsa keys is possible.
Is there any plans about ecc cert option？

Details,please read this https://eff-certbot.readthedocs.io/en/stable/using.html#using-ecdsa-keys

**Comment by adferrand** [comment]
Well, given the amount of time I passed to help implementing this feature on Certbot side, it would be a shame to not have it here, isn't it? I prepare that.

**Comment by adferrand** [comment]
This is done with 3.15.0.
