### ISSUE TITLE
Is pynamecheap still needed as a dependency

### ISSUE THREAD

**Issue by a16bitsysop** [adferrand/dnsrobocert#581]
pynamecheap is listed in poetry.lock
https://github.com/adferrand/dnsrobocert/blob/c2871b16109addb6d90ecd7097a184704ebdb018/poetry.lock#L789

It is also installed if dnsrobocert is installed with pip, but the lexicon Namecheap provider does not use it and I can't see any reference to it in dnsrobocert apart from poetry.lock and pyproject.toml

**Comment by adferrand** [comment]
Indeed I refactored `lexicon`, the underlying library that manages the DNS challenges, so that the `namecheap` provider is now a standalone that do not required `pynamecheap` library. I fix the dependencies.

Thanks a lot for your report !
