### ISSUE TITLE
Error if lets-encrypt-r3-cross-signed.pem is present

### ISSUE THREAD

**Issue by Azertooth** [adferrand/dnsrobocert#600]
I got this non-fatal error tailing my certificate renewing and I cannot move that file fron is current folder

dnsrobocert  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dnsrobocert  | Certificate not yet due for renewal; no action taken.
dnsrobocert  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
dnsrobocert  | ----------
dnsrobocert  | 2021-12-07 13:55:46 dnsrobocert dnsrobocert.core.main[1] INFO Revoke and delete certificates if needed
dnsrobocert  | 2021-12-07 13:55:46 dnsrobocert dnsrobocert.core.main[1] INFO Removing the certificate lets-encrypt-r3-cross-signed.pem
dnsrobocert  | 2021-12-07 13:55:46 dnsrobocert dnsrobocert.core.utils[1] INFO Launching command: /usr/local/bin/python3 -m dnsrobocert.core.certbot revoke -n --config-dir /etc/letsencrypt --work-dir /etc/letsencrypt/workdir --logs-dir /etc/letsencrypt/logs --server https://acme-v02.api.letsencrypt.org/directory --cert-path /etc/letsencrypt/live/lets-encrypt-r3-cross-signed.pem/cert.pem
dnsrobocert  | ----------
dnsrobocert  | Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
dnsrobocert  | An unexpected error occurred:
dnsrobocert  | NotADirectoryError: [Errno 20] Not a directory: '/etc/letsencrypt/live/lets-encrypt-r3-cross-signed.pem/cert.pem'
dnsrobocert  | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /etc/letsencrypt/logs/letsencrypt.log or re-run Certbot with -v for more details.
dnsrobocert  | ----------
dnsrobocert  | 2021-12-07 13:55:47 dnsrobocert dnsrobocert.core.main[1] ERROR An error occurred during DNSroboCert watch:
dnsrobocert  | 2021-12-07 13:55:47 dnsrobocert dnsrobocert.core.main[1] ERROR Command '['/usr/local/bin/python3', '-m', 'dnsrobocert.core.certbot', 'revoke', '-n', '--config-dir', '/etc/letsencrypt', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs', '--server', 'https://acme-v02.api.letsencrypt.org/directory', '--cert-path', '/etc/letsencrypt/live/lets-encrypt-r3-cross-signed.pem/cert.pem']' returned non-zero exit status 1.
dnsrobocert  | Traceback (most recent call last):
dnsrobocert  |   File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/main.py", line 116, in _watch_config
dnsrobocert  |     _process_config(
dnsrobocert  |   File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/main.py", line 79, in _process_config
dnsrobocert  |     certbot.revoke(runtime_config_path, directory_path, domain, lock)
dnsrobocert  |   File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/certbot.py", line 150, in revoke
dnsrobocert  |     utils.execute(
dnsrobocert  |   File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/utils.py", line 60, in execute
dnsrobocert  |     raise error
dnsrobocert  |   File "/usr/local/lib/python3.9/site-packages/dnsrobocert/core/utils.py", line 50, in execute
dnsrobocert  |     call(command, shell=shell, env=env)
dnsrobocert  |   File "/usr/local/lib/python3.9/subprocess.py", line 373, in check_call
dnsrobocert  |     raise CalledProcessError(retcode, cmd)
dnsrobocert  | subprocess.CalledProcessError: Command '['/usr/local/bin/python3', '-m', 'dnsrobocert.core.certbot', 'revoke', '-n', '--config-dir', '/etc/letsencrypt', '--work-dir', '/etc/letsencrypt/workdir', '--logs-dir', '/etc/letsencrypt/logs', '--server', 'https://acme-v02.api.letsencrypt.org/directory', '--cert-path', '/etc/letsencrypt/live/lets-encrypt-r3-cross-signed.pem/cert.pem']' returned non-zero exit status 1.

**Comment by adferrand** [comment]
If you can share here the configuration file you are using (with API keys and critical stuff edited) this would be great.

Thanks!

**Comment by Azertooth** [comment]
Thank you @adferrand for joining the conversation! actually I solved that by moving away the lets-encrypt-r3-cross-signed.pem from that folder, I could actually do that by editing the relative webserver configuration, my bad. I can close this now
