### ISSUE TITLE
problem when certificate already exists

### ISSUE THREAD

**Issue by Tidle999** [adferrand/dnsrobocert#74]
Hello,

when the certificates are already existing, the container is not able the renew the certificate (when complety recreating the docker), when i delete the certificates first, its working. is there a way to delete them first, or should this work?

**Comment by adferrand** [comment]
Hello @Tidle999, I completely rewrote the Docker logic, which is now named `adferrand/dnsrobocert`. Do you still see this issue with the latest version of dnsrobocert ?

Kindly regards.

**Comment by NilsFrkal** [comment]
I have the same problem. When I start the new docker image after generating the config.yml I get:

dnsrobocert.core.main[1] INFO Starting DNSroboCert.
dnsrobocert.core.config[1] ERROR Error while validating dnsrobocert configuration:
Certificate with name `*.mydomain.com` is duplicated.

@Tidle999 how did you delete the certificate ... I can't even find it.

certbot delete --cert-name *.mydomain.com
No certificate found with name *.mydomain.com

but still getting the duplicate error.

Thank you.

**Comment by NilsFrkal** [comment]
I figured it out ... the generated config.yml had a wildcard in front of the certificate name

- domains:
  - '*.mydomain.com'
  - mydomain.com
  name: '*.mydomain.com'

I removed the '*.' in front of the name i.e. name: 'mydomain.com' and now it works.

Thanks Nils

**Comment by adferrand** [comment]
Ah yes, I forgot to properly convert wildcard names in legacy migration. I will fix that tomorrow. Sorry for the trouble...
