### ISSUE TITLE
Providing Multi Arch images

### ISSUE THREAD

**Issue by a16bitsysop** [adferrand/dnsrobocert#76]
I have successfully run this on my arm64 SBC but I had to rebuild the image from the dockerfile to get an arm64 version, are you going to have multi arch images

**Comment by adferrand** [comment]
Yes, this is on my backlog.

**Comment by a16bitsysop** [comment]
Great

**Comment by a16bitsysop** [comment]
I did a multi arch build and it fails on 390x as rsyslogd is not available on that platform, if I change it to syslog-ng in the Dockerfile it builds and I have run it but I couldn’t see how rsyslogd was started or called so I don’t know if will work as intended with the change.

**Comment by adferrand** [comment]
First, I reopen the issue to keep track of this feature, and remember of any technical specs that could emerge from the discussion.

**Comment by adferrand** [comment]
Rsyslogd is installed to let cron run correctly, if I remember correctly. So I you do not see errors at start, and during a day (so the cron jobs have been run), I think you are good.

Note that I am about to publish a major refactoring of the project, rewritten in Python, in which the cron process is not needed anymore, and so does rsyslog or syslog-ng.

**Comment by a16bitsysop** [comment]
Thanks

**Comment by patrickpissurno** [comment]
Hi! Please take a look at [my fork](https://github.com/patrickpissurno/rpi-docker-letsencrypt-dns). It's an automated multiarch build of this image supporting amd64, arm64 and armhf (armv7).

An up-to-date version of the [upstream source code](https://github.com/adferrand/docker-letsencrypt-dns) is fetched, built and released to my [Docker Hub](https://hub.docker.com/r/patrickpissurno/rpi-docker-letsencrypt-dns) daily (automated via [Travis CI](https://travis-ci.org/patrickpissurno/rpi-docker-letsencrypt-dns/)).

You just have to replace every `adferrand/letsencrypt-dns` occurrence with `patrickpissurno/rpi-docker-letsencrypt-dns`.

Give it a try!

I'll be working with @adferrand to try and get multiarch builds for the main image. But for the time being, just switch to mine if you're using arm.

**Comment by a16bitsysop** [comment]
Thanks will have a look at your one, I have tried a few times myself to get non amd64 images with docker hub autobuild but I always end up with an amd64 image.  Your way looks easier, it doesn't need any pre build hooks then?

I think it took me about 12hours to do the multi arch build on an old laptop!

**Comment by adferrand** [comment]
Hello all: I propose to move to #77 to continue the discussion.
