### ISSUE TITLE
config.yml parsing fails for generated YAML file integers (dirs|files_mode).

### ISSUE THREAD

**Issue by r-pufky** [adferrand/dnsrobocert#85]
`dirs_mode` and `files_mode` are `integers`; however they require a leading zero to be properly interpreted for the configuration parser. Representing permissions without a leading zero **will** cause the parser to fail (as well as not actually representing explicit file permissions correctly).

When using configuration management to manage this file for deployments, if YAML is used as a datastore for the CM engine, integers/octals are rendered **without** the leading zero, leading to a configuration load error for dnsrobocert.

The easy way to fix this is to use a **string** value, e.g. `'0750'` or **allowing** a string value to be used as an alternate, accepted way to explicitly set permissions.

**Comment by adferrand** [comment]
Hello! Thanks for your report.

I just published the version 3.0.2, that allows to use integers or strings to define the octal modes.

**Comment by r-pufky** [comment]
Confirmed working with latest image. Thanks!
