### ISSUE TITLE
Migration script wrongly converts environment variable LEXICON_TRANSIP_USERNAME

### ISSUE THREAD

**Issue by Steffaan** [adferrand/dnsrobocert#87]
When using the migration script te environment variable LEXICON_TRANSIP_USERNAME is converted into username in the provider_options section while it should be auth_username.

**Comment by adferrand** [comment]
Hello @Steffaan, yes it does so because the mapping of `LEXICON_PROVIDER_PARAM` to `auth_param` is deprecated in Lexicon since 3.0.0, released at the end of 2018.

You are supposed to use the complete parameter name, so `LEXICON_PROVIDER_AUTH_PARAM`.

**Comment by Steffaan** [comment]
Ah, I did not know that. Thx fot your quick response!
