### ISSUE TITLE
Where can LEXICON_TTL be specified in new config.yml

### ISSUE THREAD

**Issue by Steffaan** [adferrand/dnsrobocert#88]
When using Transip by default a DNS record is created with a TTL of 1 hour. (I don't know if that is the same for other providers).

Before the upgrade to version 3 (in letsencrypt-dns) we had the option to change the ttl by the use of the environment variable LEXICON_TTL. 

How can this option be specified in the config.yml. I already tried specifying ttl: 180 in the provider_options but that doesn't work.

**Comment by adferrand** [comment]
It was not possible, I forgot this configuration parameter during the migration.

I am preparing a new release. It includes a proper migration of `LEXICON_TTL` from the legacy configuration.
