### ISSUE TITLE
Email validation is too strict

### ISSUE THREAD

**Issue by davidyuk** [adferrand/dnsrobocert#97]
I have put an email address of my coworker ending with `.digital` that we are already using for letsencrypt to `acme.email_account`, but it fails with an error:

> ERROR Error while validating dnsrobocert configuration for node path /acme/email_account:
'letsencrypt@....digital' does not match '^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$'

so I had to use my own email that ends with `.com`🙁

**Comment by chraledev** [comment]
An email address containing a plus sign also fails this "validation", as will plenty of other RFC compliant addresses.

**Comment by twiedenbein** [comment]
I ended up exec'ing into the container, `vi /usr/lib/python3.8/site-packages/dnsrobocert/schema.yml`, and commented out the `pattern: ^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$` line under `email_account:` for now as a workaround.

**Comment by adferrand** [comment]
Sorry I was really busy and could not have the time to work on the issues. I will fix that today.

**Comment by adferrand** [comment]
I relaxed the control with version 3.3.1, making it follow the rfc more closely. Sorry for the convenience.
